export const GET_COURSE = "GET_COURSE"
export const GET_COURSE_DETAIL = "GET_COURSE_DETAIL"
export const STORE_COURSE = "STORE_COURSE"
export const DELETE_COURSE = "DELETE_COURSE"
export const RESET_COURSE = "RESET_COURSE"

//THIS IS ENUM OF THE ACTION OF THE COURSE.
